name: github pages

on: push

jobs:
  workflow:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install
        run: yarn
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test
